"""Add OTP, Chatroom, Message, Subscription tables

Revision ID: 66afd19add1e
Revises: 9fe64fd6b53e
Create Date: 2025-07-11 14:44:25.177691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66afd19add1e'
down_revision: Union[str, Sequence[str], None] = '9fe64fd6b53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
